services:
  flask-app:
    build: .
    ports:
      - '5001:5001'
    volumes:
      - /var/log:/var/log
    restart: always

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    restart: always

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    restart: always

  loki:
    image: grafana/loki:latest
    ports:
      - '3100:3100'
    restart: always

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - /var/log:/var/log
    ports:
      - '9080:9080'
    restart: always
