auth_enabled: false
server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

scrape_config:
  - job_name: local-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /home/arsokolov/cicd_6/log.log
