server:
  http_listen_port: 9080
  grpc_listen_port: 9095

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/api/prom/push

scrape_configs:
  - job_name: flask-app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: flask-app
          __path__: /var/log/*.log  # Убедитесь, что этот путь соответствует логам вашего приложения

